version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME
      - POSTGRES_USER
      - DATABASE_HOST
      - DATABASE_PORT
      - POSTGRES_PASSWORD
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_URL
      - PGPASSWORD
      - MAILER_USER
      - MAILER_PASSWORD
      - API_KEY
    command: bundle exec rails server -b 0.0.0.0
  sidekiq:
    build: .
    volumes:
      - .:/myapp
    depends_on:
      - redis
    environment:
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_URL
      - MAILER_USER
      - MAILER_PASSWORD
      - API_KEY
    command: bundle exec sidekiq
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - DATABASE_NAME
      - POSTGRES_USER
      - DATABASE_HOST
      - DATABASE_PORT
      - POSTGRES_PASSWORD
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_URL
      - PGPASSWORD
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
    command:
      - redis-server