version: "3.9"
services:
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME
      - POSTGRES_USER
      - DATABASE_HOST
      - DATABASE_PORT
      - POSTGRES_PASSWORD
      - REDIS_HOST
    command: bundle exec rails server -b 0.0.0.0
  sidekiq:
    build: .
    volumes:
      - .:/myapp
    command: bundle exec sidekiq
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - DATABASE_NAME
      - POSTGRES_USER
      - DATABASE_HOST
      - DATABASE_PORT
      - POSTGRES_PASSWORD
      - REDIS_HOST
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis